let books = [
  {
    id: 1,
    title: "Illuminate apparition",
    number_of_pages: 150,
    excerpt:
      "https://lien/relatif/vers/un/ficeeehier/pdf/d_une/page/de/l_ouvrageretretre",
    summary:
      "Ce livre écrit par John Doe, décrit l'histoire d'un jeune homme...",
    publisher: "Sushi Productions",
    date_of_publication: "02-02-2024",
    book_cover: "http://localhost:3901/images/cover1.jpg",
    userId: 5,
    writerId: 1,
    categoryId: 1,
  },
  {
    id: 2,
    title: "Illuminate desapparition",
    number_of_pages: 152,
    excerpt:
      "https://lien/relatif/vers/un/fichier/eepdf/d_une/page/de/l_ouvragertetert",
    summary:
      "Ce livre écrit par John Doe, décrit l'histoire d'une jeune femme...",
    publisher: "Sushi Productions",
    date_of_publication: "02-02-2025",
    book_cover: "http://localhost:3901/images/cover2.jpg",
    userId: 4,
    writerId: 1,
    categoryId: 1,
  },
  {
    id: 3,
    title: "Book 3",
    number_of_pages: 153,
    excerpt:
      "https://lien/relatif/vers/un/fichier/eepdf/d_une/page/de/l_ouvrageertret",
    summary: "Summary of book 3...",
    publisher: "Publisher Name",
    date_of_publication: "02-02-2026",
    book_cover: "http://localhost:3901/images/cover3.jpg",
    userId: 3,
    writerId: 2,
    categoryId: 2,
  },
  {
    id: 4,
    title: "Book 4",
    number_of_pages: 154,
    excerpt:
      "https://lien/relatif/vers/un/ficeheeier/pdf/d_une/page/de/l_ouvragetertre",
    summary: "Summary of book 4...",
    publisher: "Publisher Name",
    date_of_publication: "02-02-2027",
    book_cover: "http://localhost:3901/images/cover4.jpg",
    userId: 2,
    writerId: 2,
    categoryId: 2,
  },
  {
    id: 5,
    title: "Book 5",
    number_of_pages: 155,
    excerpt:
      "https://lien/relatif/vers/un/fichier/peedf/d_une/pagee/de/l_ouvrageertert",
    summary: "Summary of book 5...",
    publisher: "Publisher Name",
    date_of_publication: "02-02-2028",
    book_cover: "http://localhost:3901/images/cover5.jpg",
    userId: 1,
    writerId: 3,
    categoryId: 3,
  },
  {
    id: 6,
    title: "Book 6",
    number_of_pages: 156,
    excerpt:
      "https://lien/relaeetif/versee/un/fichier/pdf/d_une/page/de/l_ouvrageeeertreeet",
    summary: "Summary of book 6...",
    publisher: "Publisher Name",
    date_of_publication: "02-02-2029",
    book_cover: "http://localhost:3901/images/cover6.jpg",
    userId: 5,
    writerId: 3,
    categoryId: 3,
  },
  {
    id: 7,
    title: "Book 7",
    number_of_pages: 157,
    excerpt:
      "https://lien/relatif/vers/eun/fichier/pdf/d_unee/page/de/l_oeeuvrageretertereeee",
    summary: "Summary of book 7...",
    publisher: "Publisher Name",
    date_of_publication: "02-02-2030",
    book_cover: "http://localhost:3901/images/cover7.jpg",
    userId: 4,
    writerId: 4,
    categoryId: 4,
  },
  {
    id: 8,
    title: "Book 8",
    number_of_pages: 158,
    excerpt:
      "https://lien/relaetif/veres/un/fichier/pdf/d_une/eepage/de/l_ouvrage",
    summary: "Summary of book 8...",
    publisher: "Publisher Name",
    date_of_publication: "02-02-2031",
    book_cover: "http://localhost:3901/images/cover8.jpg",
    userId: 3,
    writerId: 4,
    categoryId: 4,
  },
  {
    id: 9,
    title: "Book 9",
    number_of_pages: 159,
    excerpt: "https://lien/relatif/vers/un/fichieeer/pdf/d_une/paeege/de/e",
    summary: "Summary of book 9...",
    publisher: "Publisher Name",
    date_of_publication: "02-02-2032",
    book_cover: "http://localhost:3901/images/cover9.jpg",
    userId: 2,
    writerId: 5,
    categoryId: 5,
  },
  {
    id: 10,
    title: "Book 10",
    number_of_pages: 160,
    excerpt:
      "https://lieen/eeeerelatif/e/un/fichier/pdf/d_une/page/de/l_ouvrage",
    summary: "Summary of book 10...",
    publisher: "Publisher Name",
    date_of_publication: "02-02-2033",
    book_cover: "http://localhost:3901/images/cover10.jpg",
    userId: 1,
    writerId: 5,
    categoryId: 5,
  },
];

export { books };
