let users = [
  {
    id: 1,
    firstName: "etml",
    lastName: "etml",
    nickName: "etml",
    email: "etml@eduvaud.ch",
    password: "etml",
    dateEntry: "02-02-2025",
    isAdmin: false,
  },
  {
    id: 2,
    firstName: "etml2",
    lastName: "etml2",
    nickName: "etml2",
    email: "etml2@eduvaud.ch",
    password: "etml2",
    dateEntry: "02-02-2025",
    isAdmin: false,
  },
  {
    id: 3,
    firstName: "etml3",
    lastName: "etml3",
    nickName: "etml3",
    email: "etml3@eduvaud.ch",
    password: "etml3",
    dateEntry: "02-02-2025",
    isAdmin: false,
  },
  {
    id: 4,
    firstName: "etml4",
    lastName: "etml4",
    nickName: "etml4",
    email: "etml4@eduvaud.ch",
    password: "etml4",
    dateEntry: "02-02-2025",
    isAdmin: false,
  },
  {
    id: 5,
    firstName: "etml5",
    lastName: "etml5",
    nickName: "etml5",
    email: "etml5@eduvaud.ch",
    password: "etml5",
    dateEntry: "02-02-2025",
    isAdmin: false,
  },
  {
    id: 6,
    firstName: "admin",
    lastName: "admin",
    nickName: "admin",
    email: "admin@eduvaud.ch",
    password: "admin",
    dateEntry: "02-02-2025",
    isAdmin: true,
  },
];
export { users };
